### PR TITLE
chore(hooks-cmake): Remove hooks we dont have

### PR DESCRIPTION
**Pull request by Kitzunu**

### CODE REVIEW

**Review by pangolp — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
cc @Yehonal

**Comment by Kitzunu** [comment]
They don't even exist in the core

**Comment by Yehonal** [comment]
We have them...

image

Maybe some have been renamed and never updated here? I cannot check all of them right now but one that you removed is in the main CmakeLists

These hooks are used by the modules to apply certain operations during the compilation, and we should add more of them not remove

**Comment by Kitzunu** [comment]
ah ok I only checked /src

**Pull request closed without merging**
