### PR TITLE
Update installation.md, changed cmake PATH adding $HOME variable

### PR DESCRIPTION
**Pull request by Helias**
As suggested the discord user **Stevej**, I put the $HOME variable in the cmake path instead of /home/youruser/ (for Linux and Mac).

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
thanks @Helias and @pangolp

**Comment by BarbzYHOOL** [comment]
good

**Comment by pangolp** [comment]
Not at all, on the contrary, thank you for taking the time to make the change, I hope it will help you. **The only thing I would add, would be just in case, to clarify that $HOME is a variable that saves the information to the directory of the user who is with the active session. For the doubts that this with the user root for example and then does not find the compilation.**

**Comment by Helias** [comment]
Umh, yep, if a user is logged as root the path change, I'm making another PR

**Comment by FrancescoBorzi** [comment]
feel free to send more PRs to improve the wiki :)

you don't need to clone it locally, just edit the page via github

**Pull request merged**
