### PR TITLE
feat: Dealing with SQL files and FLAGS

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
How to remove, add or invert flags in SQL

Might not be put at the right place, dunno, did it in a hurry

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Hmm apparently there is something about it already but i didn't see where and it looks less simple than mine https://github.com/azerothcore/wiki/pull/43

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL I think we can merge this too.

**Comment by BarbzYHOOL** [comment]
ok but i'm annoyed by the duplicate info on both pages :'(

**Comment by Kitzunu** [comment]
From what I see I cant find a reference to that other page on any page on the wiki and it feels more better to have it under the how to deal with sql section imo

**Comment by Helias** [comment]
What about merge? @BarbzYHOOL

**Comment by Kitzunu** [comment]
@BarbzYHOOL If I should be perfectly honest, your changes make more sense, are simpler and in the correct place.

I'd suggest removing the other version that was previously made.

**Comment by BarbzYHOOL** [comment]
ok, go helias :D

**Pull request merged**
