### PR TITLE
Arch

### PR DESCRIPTION
**Pull request by Viste**
dont know from what i need to start but all arch users need enable aur and then they can easy install azerothcore through aur.
install not full only core now.

### CODE REVIEW

**Comment by Helias** [comment]
Nice!

**Comment by daxcpp** [comment]
The aur package doesn't work, I tried to install it but there was a problem with the dependencies (libmysqlclient57 and ace). I think that you need to add ace and libmysqlclient57 (from aur) in the PKGBUILD.

**Comment by Viste** [comment]
@daxcpp hm my pacman get ace and libmysqlclient57 from aur X_x ok i look on it

**Comment by Viste** [comment]
ok i can't run AUR dependencies in PKGBUILD so i move its to optdepends

**Comment by daxcpp** [comment]
Ok thank you! I will test it as soon as I can and I will give you a feedback

**Comment by Viste** [comment]
libmysqlclient57 changed to MariaDB and moved to depends.

**Comment by daxcpp** [comment]
I tried to install it again but I still have errors

**Comment by Viste** [comment]
what errors you get?

**Comment by daxcpp** [comment]
[log.txt](https://github.com/azerothcore/wiki/files/4176886/log.txt)

**Comment by Viste** [comment]
try now 3.0.1-2 version must be ok

**Comment by daxcpp** [comment]
Nothing has changed. When I have a while I will try to solve the problems :)

**Comment by Winfidonarleyan** [comment]
by @Viste "strange, but for me install works ok, my log https://paste2.org/M4kfKPmJ"

**Comment by daxcpp** [comment]
Sorry but I have the same errors:
[https://pastebin.com/yrNf4Nqb](log)

**Comment by Viste** [comment]
plz show ` pacman -Q | grep ace`

**Comment by daxcpp** [comment]
So I have to install ace before installing the azeroth-core package?

**Comment by daxcpp** [comment]
Ok now it worked but I think that ace it's not an optional dependency :)

**Comment by Helias** [comment]
We need to write a guide to install AzerothCore on ArchLinux with the related dependencies

**Comment by Viste** [comment]
> Ok now it works but I think that ace it's not an optional dependency :)

yes its not optional bu i can't install dependencies from AUR in PKGBUILD, so i move its to optdepends

**Comment by daxcpp** [comment]
Yes but I think that it's not optional. If you don't have ace installed the building won't be successful

**Comment by daxcpp** [comment]
Ok, I think that it's good but maybe we can try to create a group package with ace and azeroth-core

**Comment by Viste** [comment]
i think its bad install ace insade azerothcore :C 
@FrancescoBorzi @Helias @Yehonal  @BarbzYHOOL what is your suggetions 
also i need some help with text part of this shit because of my shit english

**Comment by FrancescoBorzi** [comment]
I think that ideally we should just get rid of ACE forever.... but not sure what to do until then

**Comment by BarbzYHOOL** [comment]
I am not qualified to say remove or not ACE, I just know that AC is working fine with ACE at the moment

**Pull request merged**
