### PR TITLE
fix(wiki): Include rev_gen link

### LINKED ISSUE #715: Add rev-file generator link for DB only PRs wiki
The link for the rev_generator was removed from https://www.azerothcore.org/wiki/how-to-create-a-db-pr

https://www.azerothcore.org/pages/rev-generator/

Add it back, pls & ty

### PR DESCRIPTION
**Pull request by Si1ker**
### Description

Add rev-generator link for new PRs with DB changes only (online)

### Related Issue

Closes #715

cc @Helias @FrancescoBorzi @Kitzunu

### CODE REVIEW

**Comment by Kitzunu** [comment]
Why? The file doesnt need a specific name

**Comment by Si1ker** [comment]
> Why? The file doesnt need a specific name

so you can literally name it "update" and it will not cause any issue?
cc @acidmanifesto who was the one who shared the rev file name link

**Comment by acidmanifesto** [comment]
> > Why? The file doesnt need a specific name
> 
> @Kitzunu  so you can literally name it "update" and it will not cause any issue?
> cc @acidmanifesto who was the one who shared the rev file name link

It was something relayed to me after one of the prs got merged when i was sleeping off a sugar booger session like a month or so ago.

**Comment by Si1ker** [comment]
ok closing then, I'll just name my files "update" n.n

**Pull request closed without merging**
