### PR TITLE
Windows instructions fix

### PR DESCRIPTION
**Pull request by yoreei**
BOOST_ROOT was recently changed to Boost_ROOT:

https://github.com/azerothcore/azerothcore-wotlk/pull/18283/files

Update eng and spanish wikis to reflect that.

Also, clean up old windows instructions:

- windows-vsc-core-installation.md
- vsc-requirements.md

These docs were not linked to by any other page.

### Description

- 
- 

### Related Issue

Closes

## Thank you for contributing to the AzerothCore wiki.

Remember that the wiki is currently available in English and Spanish.

- https://www.azerothcore.org/wiki/home
- https://www.azerothcore.org/wiki/es/home

### CODE REVIEW

**Comment by Kitzunu** [comment]
What is the reasoning to remove the VS Code installation?

**Comment by Kitzunu** [comment]
And if it is valid you also need to remove the reference here https://www.azerothcore.org/wiki/installation

**Comment by pangolp** [comment]
@yoreei The environment variable is still called `BOOST_ROOT`, in fact, I have it with capital letters. In fact, I was the creator of the pull request, to eliminate that warning that appeared in the cmake, so it is not necessary to make at least that change. I didn't really read the rest of the modifications.

**Comment by pangolp** [comment]
Currently you used the environment variable in upper case, but in the macro, it should go that way. For us, nothing changes. Thank you anyway, for your interest in collaborating, if you want to do so, there are many documents that may have been outdated. It would be good to review them and see what happens with them.

**Comment by yoreei** [comment]
I see, the BOOST_ROOT change is indeed not needed.

Also, no need to delete the VS Code instructions. I thought these were no longer reachable from any page in the wiki.

Closing PR.

**Pull request closed without merging**
