### PR TITLE
Documentation for the new script command SCRIPT_COMMAND_MOVEMENT (35)

### PR DESCRIPTION
**Pull request by Stoabrogga**
- Add documentation for the new script command SCRIPT_COMMAND_MOVEMENT (35)
 (see https://github.com/azerothcore/azerothcore-wotlk/pull/1721)
- Add "scripts"-link to "database-world.md" as this seems to be missing

### CODE REVIEW

**Comment by Pondaveia** [comment]
maybe add a description to it?

**Comment by Stoabrogga** [comment]
@Pondaveia 
see the changed files

**Comment by Pondaveia** [comment]
A developer may be used to read "Change movement type", but a newbie probably won't understand that this swaps the walk on path to a random movement. That's why I was wondering if a detailed description wouldn't help everyone 😄

**Comment by Stoabrogga** [comment]
Feel free to create a more detailed description and create a new PR. I don't have infinite time to spend on the AC project. After all it's a hobby, I don't get paid for this.

**Comment by Pondaveia** [comment]
I was only suggesting calm down ...

**Comment by Stoabrogga** [comment]
Me too, but it has to be in an acceptable time frame, and I just don't have that much time, sorry.

**Comment by Pondaveia** [comment]
Don't take any of this personally, I'm only trying to help things out 😞

**Comment by Stoabrogga** [comment]
I don't take any of this personally (I know, hard to tell when only communicating via text), just wanted to state my point of view. Originally I just wanted to fix an error in the log (easy SQL), this lead to implementing a new script command (not so easy: coding, building, testing) and also updating the documentation, so it doesn't get lost (like it did on TC obviously, as I found nothing about command 35). I just have to stop somewhere, because else it would continue perpetually like this.

So this PR is a good start I think, the command is documented and it doesn't get lost. Someone else can flesh it out later if necessary.

**Pull request merged**
