### PR TITLE
Auth Tables Documentation updates

### PR DESCRIPTION
**Pull request by Kitzunu**
TODO: Need to add a ` worldserver.conf` description somewhere since http://www.azerothcore.org/wiki/autobroadcast links to it.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Can the website show .txt files?

because creating worldserver.conf as a .md will be pain https://gist.github.com/Kitzunu/618196187040c82fecaff3f9a1949c7b

**Comment by Kitzunu** [comment]
Maybe we just make it inside of a command block for ease? https://gist.github.com/Kitzunu/2e182f65f77b2eef0a90201fbce5281b

@FrancescoBorzi thoughts?

**Comment by FrancescoBorzi** [comment]
@Yehonal can you assist with this? As I'm currently extremely busy

**Comment by BarbzYHOOL** [comment]
@Kitzunu can you just link to this instead https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist ??

and yes this wiki has multiple issues, we need yehonal :'(

**Pull request merged**
