### PR TITLE
sync

### PR DESCRIPTION
**Pull request by Yehonal**

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
just wanted to say that we should keep the github wiki, it's easier to use than to open PRs

**Comment by Yehonal** [comment]
The PR should be opened only from third party contributors not our devs.
The github internal wiki doesn't handle external contributions. The only
way is to give public write access with vandalism risk. Moreover this wiki
has tons of more features than the github wiki that is not enough for large
projects.

Check drassil/git-wiki to see other succesfully cases. It's used by
clearlydefined an official FOSS organization for opensource

Il Lun 18 Feb 2019, 15:07 Barbz <notifications@github.com> ha scritto:

**Comment by BarbzYHOOL** [comment]
wtf where is the wiki??

**Comment by Helias** [comment]
@BarbzYHOOL http://www.azerothcore.org/wiki/home
Now we can track the history of the wiki and everyone can open PR to edit/improve the wiki.

**Comment by Yehonal** [comment]
http://www.azerothcore.org/wiki/home

image

**Comment by BarbzYHOOL** [comment]
everybody could open PR before (just needed a github account) and we could track history as well and it was extremely easy ...

**Comment by Yehonal** [comment]
PR on github wiki are not available. Only devs can edit github wiki. As i said the alternative was to grant public write accesses to everyone for external contributions. It slows down documentation job.

If you have the evidence of PR for internal github wiki, please share it.

**Comment by BarbzYHOOL** [comment]
I asked some guys to edit the wiki long ago and they did, now they won't because they need to know how to make a pull request. I can edit this wiki that I just found on google

https://github.com/ramnathv/test-wiki/wiki

**Comment by Yehonal** [comment]
Yes you can edit and write any kind of shits there :D without the ability to moderate the contribution from external people before they write. It cannot be called PR (Pull Request). It's an odd public whitepaper and we don't have the wikipedia team to moderate it.

Now, if someone is trusty, you can just create a "wiki" team for this repo and add him there, devs are already enabled.

**Comment by BarbzYHOOL** [comment]
> Yes you can edit and write any kind of shits there 

never happened


Well I don't think all of this is good but if you guys are ready to write on the wiki alone, it's fine

**Comment by FrancescoBorzi** [comment]
I think there was a misunderstanding: the process to edit the new wiki is not as hard as opening a normal PR (like in the main repo). It's much more easy since you just click edit, edit the page as you would normally do, then github automatically creates the PR for you. So for users is not harder than before, it's the same complexity. The only difference (from user side) is that they have to wait a bit until the change is displayed.

**Comment by Yehonal** [comment]
Please read the 2018 roadmap: http://azerothcore.altervista.org/wp/roadmap-2018/

**Pull request merged**
