### PR TITLE
Add (Translation\ES): create-a-module file in Spanish

### PR DESCRIPTION
**Pull request by pangolp**
### Description

The create-a-module file is added in Spanish.

### Related Issue

https://github.com/azerothcore/wiki/issues/539

### CODE REVIEW

**Comment by Tony931023** [comment]
@pangolp linea 11 [enviando un RP] debería ser [enviando un PR]

**Comment by pangolp** [comment]
> @pangolp linea 11 [enviando un RP] debería ser [enviando un PR]

Ya lo acomodo entonces, gracias.

**Comment by pangolp** [comment]
https://github.com/azerothcore/wiki/issues/539

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
