### PR TITLE
Example of a scrollable table

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
Go here https://github.com/azerothcore/wiki/blob/99d63b6310101c728f4146d95b3612dfea22b873/docs/smart_scripts.md and Ctrl+F `SMART_EVENT_COUNTER_SET` then look at how it looks now, instead of a super long table, it's scrollable vertically

What do you think?

it's just a test

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
with this we can't resize the table however (like a textarea/form), to have it resizable we'd need to add a JS library or write smthg and include it in the wiki default CSS if there is any

**Comment by Stoabrogga** [comment]
Looks good to me, tested it on my PC and mobile.

**Comment by Stoabrogga** [comment]
So, what should we do now with this? I think it works well and would greatly improve the usability of the wiki pages.

**Comment by FrancescoBorzi** [comment]
@Stoabrogga LGTM, feel free to merge

**Comment by Helias** [comment]
Agree, for me this PR could be merged, it will improve the wiki.

**Comment by Stoabrogga** [comment]
Ok, is there an easy way to adjust all tables on all pages this way? This PR is a draft and contains only the change for a single table.

**Comment by Stoabrogga** [comment]
Closing as this was only a draft. See #100

**Comment by BarbzYHOOL** [comment]
@Stoabrogga if we can edit the CSS then maybe we can just add 

```
table
{
    height: 400px;
    max-height: 400px;
}
```

or something like that

**Comment by Stoabrogga** [comment]
On second thought don't know if it is needed everywhere, perhaps just for the bigger tables.

**Comment by BarbzYHOOL** [comment]
Note: only max-height is needed, not height

**Pull request closed without merging**
