### PR TITLE
Update windows-requirements for OpenSSL 3

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
### Related Issue
- https://github.com/azerothcore/azerothcore-wotlk/pull/13354

## Thank you for contributing to the AzerothCore wiki.

Remember that the wiki is currently available in English and Spanish.

- https://www.azerothcore.org/wiki/home
- https://www.azerothcore.org/wiki/es/home

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]
Will OpenSSL 1.1.x still work?

**Comment by heyitsbench** [comment]
> Will OpenSSL 1.1.x still work?

Yes.

**Comment by Winfidonarleyan** [comment]
> Will OpenSSL 1.1.x still work?

yes, this tested

**Comment by pangolp** [comment]
Thanks.

**Comment by heyitsbench** [comment]
This should only have been merged when https://github.com/azerothcore/azerothcore-wotlk/pull/13354 was merged.

**Comment by Helias** [comment]
mistakes have been made hehe

I don't think it's a big issue, but yep, would be great to align the wiki only when that PR was merged

**Comment by pangolp** [comment]
> This should only have been merged when [azerothcore/azerothcore-wotlk#13354](https://github.com/azerothcore/azerothcore-wotlk/pull/13354) was merged.

Yes, my mistake.

**Comment by pangolp** [comment]
> mistakes have been made hehe
> 
> I don't think it's a big issue, but yep, would be great to align the wiki only when that PR was merged

Yes, evidently I saw wrong, and I thought it was already merged, then I realized it was still open.

**Comment by Kitzunu** [comment]
> mistakes have been made hehe
> 
> I don't think it's a big issue, but yep, would be great to align the wiki only when that PR was merged

It is a big issue as you can't compile with OpenSSL 3.0.

But I have reverted all PRs that was merged.

**Pull request merged**
