### PR TITLE
Update `.go xyz` description for AC changes

### PR DESCRIPTION
**Pull request by kjack9**
### Description
Updates the description on `.go xyz` based on https://github.com/azerothcore/azerothcore-wotlk/pull/17772

### Related Issue
https://github.com/azerothcore/azerothcore-wotlk/pull/17772

## Thank you for contributing to the AzerothCore wiki.

Remember that the wiki is currently available in English and Spanish.

- https://www.azerothcore.org/wiki/home
- https://www.azerothcore.org/wiki/es/home

### CODE REVIEW

**Comment by kjack9** [comment]
Tagging @pangolp  as requested.

**Review by Helias — APPROVED** [review]

**Comment by pangolp** [comment]
I can't see the difference, but I think it's okay. I don't have permissions to merge it.

**Comment by pangolp** [comment]
I already managed to see the change. I think it's okay. I'm using my cell phone, I couldn't see well haha

**Comment by kjack9** [comment]
> I already managed to see the change. I think it's okay. I'm using my cell phone, I couldn't see well haha

Oh, sorry - the PR template says to ping you for Spanish translation.

**Pull request merged**
