### PR TITLE
Adding the `quest_offer_reward_locale` table

### PR DESCRIPTION
**Pull request by pangolp**
## Description

Documentation is added to the table

## Screenshots (if appropriate):
quest_offer_reward_locale-1
quest_offer_reward_locale-2

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
shall we add this to the index too? so it can be reached

**Comment by pangolp** [comment]
> shall we add this to the index too? so it can be reached

Yes, the links should work.
I tried it at https://stackedit.io/app and they worked. :)

**Comment by FrancescoBorzi** [comment]
same here, good job!

**Comment by pangolp** [comment]
Thanks @FrancescoBorzi

**Pull request merged**
