### PR TITLE
Simple Changes and Updated Sidebar.html (on the ES side)

### PR DESCRIPTION
**Pull request by TheSCREWEDSoftware**
### Description

- Updated "Note" to reflect the English Version in the Client-Setup (ES)
- Added Codeblock to "set realmlist" in Client-Setup (ES)
- Changed Sidebar.html (the spanish part only) to reflect the English version
- Added "Help" onto "Home" (ES)

### Related Issue

Closes

## Thank you for contributing to the AzerothCore wiki.

Remember that the wiki is currently available in English and Spanish.

- https://www.azerothcore.org/wiki/home
- https://www.azerothcore.org/wiki/es/home

@pangolp There was no change in Written Spanish, but im tagging since is your job done (the wiki es)

### CODE REVIEW

**Comment by pangolp** [comment]
There's no problem with being labeled or consulted. Whenever I can, I review it and try to give my opinion.

**Review by pangolp — APPROVED** [review]
Thanks.

**Comment by pangolp** [comment]
What happened that you closed the pull request?

**Comment by TheSCREWEDSoftware** [comment]
I didn't even realise that this wasn't been merged, I was doing some re-organising of the things, tomorrow when I'm home on the pc i will get this fixed.

**Comment by TheSCREWEDSoftware** [comment]
@pangolp remade the request: https://github.com/azerothcore/wiki/pull/964

**Pull request closed without merging**
