### PR TITLE
Updated Spanish Docs Folder

### PR DESCRIPTION
**Pull request by TheSCREWEDSoftware**
### Description
- Linux, MacOS and Windows NavBars/Paths have been updated (to project the same as the English version)
- Created Classic Instaltion in the Spanish Folder and Translated It (majority with the help of google, so it wouldn't be in english).
- Created MacOS Core Installationin the Spanish Folder and Translated It (majority with the help of google, so it wouldn't be in english).
- Corrected in Installation the Path for Classic-Instalation.

### Related Issue

The translate may be off or not, may be worded strangely by being european, I can't fully confirm or deny it.

## Thank you for contributing to the AzerothCore wiki.

Remember that the wiki is currently available in English and Spanish.

- https://www.azerothcore.org/wiki/home
- https://www.azerothcore.org/wiki/es/home

 @pangolp

### CODE REVIEW

**Comment by TheSCREWEDSoftware** [comment]
Just In case doesn't go throw,  @pangolp Updates for your Translation

**Comment by pangolp** [comment]
> Just In case doesn't go throw,  @pangolp Updates for your Translation

Check the document from your cell phone and it seems to be correct. Thanks for the input.

**Comment by TheSCREWEDSoftware** [comment]
> > Just In case doesn't go throw,  @pangolp Updates for your Translation
> 
> Check the document from your cell phone and it seems to be correct. Thanks for the input.

@pangolp Please confirm me that I read it right, You've checked the changes on your phone and all seems to be correct?

**Review by pangolp — APPROVED** [review]
It seems to be correct. Thanks.

**Comment by pangolp** [comment]
If there is a fault, it can be corrected, it is not necessary for it to be perfect either. It has to be understood, but if in the case that someone considers that in the future it can be written in a different way, it is edited and that's it. After all, it is a complement to the documentation in English.

**Review by sudlud — APPROVED** [review]

**Comment by sudlud** [comment]
thanks for the PR!

**Pull request merged**
