### PR TITLE
fix: Requirements for deb 8

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
big edit

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
also on debian 10 section, there is mariadb instead of mysql, why??

**Comment by BarbzYHOOL** [comment]
I'm wondering if mariadb is the default mysql server on deb 10 now or if we should replace with "default-mysql-server"

I don't have deb 10

**Comment by BarbzYHOOL** [comment]
yes I think it is, so we can leave it as it is, it's the same in the end I bet.


I added more modifications for the cmake part

**Comment by Stoabrogga** [comment]
@BarbzYHOOL 
There are also two other ways to get the latest cmake on Debian, perhaps you could add these to your PR:
1. Get the binaries from cmake.org, e.g.:
```
sudo apt purge --auto-remove cmake
version=3.15
build=3
mkdir ~/temp
cd ~/temp
wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
tar -xzvf cmake-$version.$build.tar.gz
cd cmake-$version.$build/
./bootstrap
make
sudo make install
```
2. Use snap (see https://snapcraft.io/install/cmake/debian):
```
sudo apt update
sudo apt install snapd
sudo snap install cmake --classic
```

**Comment by Helias** [comment]
```
You might need to add the stretch-backports repositories to APT in order to install clang-6.x+ and cmake v3.8+.
```
@BarbzYHOOL show how to do this in the wiki.

Anyway, I think that the easiest way to install the last version of cmake, is using the python package manager.

**Comment by BarbzYHOOL** [comment]
Well I think people should google "how to add backports repo" else we will just copy paste existing tutorials for no reason

**Comment by Helias** [comment]
I want to provide any kind of tutorials because in one month two debian users asked me help, indeed I discovered that you can install cmake through the python package manager very easily.

I would suggest that way because it's really easy, just need two commands.

**Comment by BarbzYHOOL** [comment]
I could add this link https://backports.debian.org/Instructions/

**Comment by Helias** [comment]
We can show both ways, maybe in some links like

install cmake through [backports](https://backports.debian.org/Instructions/) or using [the python package manager](https://stackoverflow.com/a/52265521/5081063).

I am really convinced that using the python package manager is easier.

**Comment by Helias** [comment]
Imported edits here https://github.com/azerothcore/wiki/pull/179

**Pull request closed without merging**
