### PR TITLE
Update Windows installation to more accurately reflect CMake steps.

### PR DESCRIPTION
**Pull request by heyitsbench**
### Description

- Changes wording from a checkbox to a multiple choice selection.

### Related Issue

Closes unreported issue.

## Thank you for contributing to the AzerothCore wiki.

Remember that the wiki is currently available in English and Spanish.

- https://www.azerothcore.org/wiki/home
- https://www.azerothcore.org/wiki/es/home

### CODE REVIEW

**Comment by Kitzunu** [comment]
Depends how correct we want to be, because setting it to all will also compile the database updater, which isn't needed

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
I don't think that the end-user would mind, but we could specify  it in the wiki

**Comment by pangolp** [comment]
Thank you for the contribution. But I think that might be confusing to some people. Unless we look for other words. It is good, to mention, that by checking it, you can compile the extractors and in that way, get the data from the client, instead of downloading it. Not to mention, you can extract in different languages (which I'm not sure if that is really necessary or not, or if that influences anything when obtaining / using such information). @heyitsbench

**Comment by heyitsbench** [comment]
> because setting it to all will also compile the database updater, which isn't needed

I can change it to maps-only if need be, but based on the next steps the wiki provides (Which is running the extractors, no mention of the DB Updater)

> It is good, to mention, that by checking it, you can compile the extractors and in that way, get the data from the client, instead of downloading it.

The issue here is that the wording implies that the option is a checkbox, which isn't the case. As for the different languages (unless I'm mistaken) the download option may eventually include the other localizations. But regardless of even that, that issue/discussion is outside the scope of this PR in my opinion.

**Comment by pangolp** [comment]
I think it's okay, we are wasting time, in a discussion that I think is going nowhere. Let's change it, and in the worst case, if someone appears and reflects, that can cause confusion, we will analyze it more deeply / reverse the change. In Spanish, the translation sounded a little confusing when I made it, but if for you in English, it is better the second way, it seems to me that it does not make sense, that we keep thinking whether or not we have to change 10 words in such a long document.

**Review by pangolp — APPROVED** [review]

**Review by Kitzunu — APPROVED** [review]
lgtm

**Pull request merged**
