### PR TITLE
Jekyll::Converters::Markdown encountered an error while converting

### PR DESCRIPTION
**Pull request by pangolp**
### Description

This is going to be hard to explain, but in trying to get a local server up, I am running into some errors. The first one is the one I'm uploading here in this PR, but then I have others that I'm investigating. The reason for these errors, I really do not know, because I am not very familiar with this technology, however, following the steps in README.md, and applying these changes, I have managed to solve several error messages, I only quote 1, so it does not become so extensive, but it is something that was repeated in most of these files.

```cmd
Starting wiki-1_github-wiki-theme_1 ... done
Attaching to wiki-1_github-wiki-theme_1
github-wiki-theme_1  | Configuration file: /srv/jekyll/_config.yml
github-wiki-theme_1  |        Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `plugins: [jekyll-paginate]` in your configuration file.
github-wiki-theme_1  |             Source: /srv/jekyll
github-wiki-theme_1  |        Destination: /srv/jekyll/_site
github-wiki-theme_1  |  Incremental build: disabled. Enable with --incremental
github-wiki-theme_1  |       Generating...
github-wiki-theme_1  |        Jekyll Feed: Generating feed for posts
github-wiki-theme_1  | Invalid Markdown processor given: GFM
github-wiki-theme_1  |                     Available processors are: rdiscount, kramdown, redcarpet
github-wiki-theme_1  |   Conversion error: Jekyll::Converters::Markdown encountered an error while converting 'docs/waypoints-information.md':
github-wiki-theme_1  |                     Bailing out; invalid Markdown processor.
github-wiki-theme_1  |              ERROR: YOUR SITE COULD NOT BE BUILT:
github-wiki-theme_1  |                     ------------------------------------
github-wiki-theme_1  |                     Bailing out; invalid Markdown processor.
wiki-1_github-wiki-theme_1 exited with code 1
```

### Related Issue

Closes

### CODE REVIEW

**Comment by pangolp** [comment]
I tried to create it through docker, following the README.md command. I remember that at one point, I had switched from GFM to kramdown, but you had mentioned to me that you were using GFM, for some reason I don't know. Even applying these changes, you still have to make other changes, in order to get a development environment up, or at least, it didn't work for me.

**Comment by pangolp** [comment]
I just moved to the master branch, where I have none of those changes applied, and just switched from `GFM` to `kramdown`, and sure enough, I get the development environment up without any problems.

kramdown

The only thing I had to do, is to copy locally the `git-wiki` folder because for some reason, it does not recognize it, in the theme that is in the repository, but if you copy it inside `_include` there is no problem.

**Comment by pangolp** [comment]
The environment, lifts, although it does not seem to recognize the links. Since they all appear in red, it is as if it is missing some configuration variable perhaps, setting and using relative paths perhaps.

localhost

**Comment by pangolp** [comment]
error

**Comment by pangolp** [comment]
If I had to make a decision, without a doubt, change inside the `_config.yml` file from `GFM` to `kramdown`. Eliminating this pull request actually. But well, it is more up to you, because despite making all these changes, even so, the local server is not up. However, with the change that I mention you if, and we would avoid us, to have to modify all those files.

**Comment by Helias** [comment]
@Yehonal

**Comment by pangolp** [comment]
Furthermore, while researching, I realized that if you add to the header what I am removing, the local link works.

```
---
redirect_from: "/requirements"
---
```

I added that to the missing page, and the link started working.

requirements

**Comment by Kitzunu** [comment]
Hard no. Do not remove the redirect stuff.

**Comment by Kitzunu** [comment]
Feel free to do it locally, but here it is needed.

**Comment by Kitzunu** [comment]
Also we changed from Kramdown to GFM because Kramdown brought issues to the wiki that GFM eliminated.

The wiki is supposed to work and run on the public website. This repo is not meant to be built around working without issue on local machines, but to work without issue to the contributors that use the wiki at the website

**Comment by Kitzunu** [comment]
And iirc the wiki is built on wokring on Gothub Sites directory and might therefore not recognize the files/links on a local setup

**Comment by Tony931023** [comment]
@pangolp I emulated this a while back when I was testing language switching.
Note that the wiki is made to work with github sites and not locally.

You are also emulating it with Docker, it gives many errors in gems and others it is easier to emulate it in linux with ubuntu http://152.206.85.117:4000

the local error that occurs with the sidebar links is for the following reason the wiki is called from the domain www.azerothcore.org in a directory called wiki and when it is emulated locally the calling directory is / not /wiki if you put a redirect that when you ask for localhost/wiki there is if it will work for you

PS: another thing that I forgot in Docker if you make any changes the wiki will not update it hot, you must restart the service to update the changes

**Comment by pangolp** [comment]
> @pangolp I emulated this a while back when I was testing language switching. Note that the wiki is made to work with github sites and not locally.
> 
> You are also emulating it with Docker, it gives many errors in gems and others it is easier to emulate it in linux with ubuntu http://152.206.85.117:4000
> 
> the local error that occurs with the sidebar links is for the following reason the wiki is called from the domain [www.azerothcore.org](http://www.azerothcore.org) in a directory called wiki and when it is emulated locally the calling directory is / not /wiki if you put a redirect that when you ask for localhost/wiki there is if it will work for you
> 
> PS: another thing that I forgot in Docker if you make any changes the wiki will not update it hot, you must restart the service to update the changes

I will review it later.

**Pull request closed without merging**
