### PR TITLE
Updating wiki layout and missing contents

### PR DESCRIPTION
**Pull request by Helias**
## Description
Added missing content to the wiki pages

## How to test
Just compare the followings files in the [master branch](https://github.com/azerothcore/wiki/tree/master/docs) and in [my fork, branch patch-2](https://github.com/azerothcore/wiki/tree/Helias-patch-2/docs), using the preview mode of the markdown file:
```
docs/character_stats.md
docs/characters.md
docs/corpse.md
docs/creature_formations.md
docs/creature_text.md
docs/guild_rank.md
docs/instance.md
docs/logs.md
docs/npc_vendor.md
docs/quest_template.md
docs/spell_dbc.md
docs/warden_checks.md
docs/worldstates.md
```

## Related Issue
Incomplete wiki, related to #11

### CODE REVIEW

**Comment by Helias** [comment]
I checked **world, auth and characters DB wiki**, I fixed a lot of table layout and I made generic improvements.

Report me any missing data or wrong table layout and I'll fix it.

For **worldstates.md** it's a mess also in the TC wiki, I improved it a bit but is still a mess

**Comment by BarbzYHOOL** [comment]
what does it look like before and after? xD

**Comment by Helias** [comment]
some tables were like:

[creature_template](http://www.azerothcore.org/wiki/creature_template)

immagine

This table also in TC is wrong.
[spell_dbc](http://www.azerothcore.org/wiki/spell_dbc)

immagine

[characters](http://www.azerothcore.org/wiki/characters) extra_flags
immagine

This last has (like a lot of tables) wrong values caused by "flags" values, now they are fixed like:

immagine

**Comment by BarbzYHOOL** [comment]
@FrancescoBorzi We should merge this imo (even if I don't know how to test it, I trust Helias xD)

**Comment by Helias** [comment]
Added how to test :P

**Pull request merged**
