### PR TITLE
Update dbc tables in the Spanish wiki

### PR DESCRIPTION
**Pull request by M4th3m4tic4l**
### Description

- It updates the basic information tables of some dbc files, such as maps, factions, etc, which were hastily made by me in the past.
- 

### Related Issue

Closes

## Thank you for contributing to the AzerothCore wiki.

Remember that the wiki is currently available in English and Spanish.

- https://www.azerothcore.org/wiki/home
- https://www.azerothcore.org/wiki/es/home

### CODE REVIEW

**Comment by Helias** [comment]
@pangolp

**Comment by Tony931023** [comment]
very good @M4th3m4tic4l  thanks for the support, @Helias  I reviewed this and it can be merged

**Comment by M4th3m4tic4l** [comment]
> very good @M4th3m4tic4l thanks for the support, @Helias I reviewed this and it can be merged

I think you can review it and it will automatically merge xd

**Comment by Helias** [comment]
Thank you, I am merging it

**Review by Helias — APPROVED** [review]

**Pull request merged**
