### PR TITLE
Update db-characters-en

### PR DESCRIPTION
**Pull request by Tony931023**
Update

    * Table structures
    * Code standards

### CODE REVIEW

**Comment by Tony931023** [comment]
Update + #584

**Comment by Tony931023** [comment]
@Kitzunu in https://www.azerothcore.org/wiki/worldstates in the part where it says

 `### known worldstate id's (entries) (more than 854 lines) `

it could not be done in a new page and refer it in https://www.azerothcore.org/wiki/worldstates#entry?

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
gracias @Tony931023 !

**Comment by Tony931023** [comment]
> 
> 
> gracias @Tony931023 !

De  nada @FrancescoBorzi 💟

**Pull request merged**
