### PR TITLE
Add a section to add-a-module.md on DBC-based modules.

### PR DESCRIPTION
**Pull request by heyitsbench**
### Description

- Adds a specific section in add-a-module.md on edge case modules that edit DBC files. Requested by Ĝ̷̳r̸̹͊a̷̜̚k̴̞̔#3563 on the AC Discord.

### Related Issue

Closes unreported issue.

## Thank you for contributing to the AzerothCore wiki.

Remember that the wiki is currently available in English and Spanish.

- https://www.azerothcore.org/wiki/home
- https://www.azerothcore.org/wiki/es/home

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
Sometimes, to overwrite some DBCs data you'll need to put the patch into your enUS/ directory, and renaming it with `patch-enUS-4.MPQ`.

it is not 100% sure that patch-Z.mpq will be loaded for last, sometimes the enUS patched are renamed as last

**Comment by heyitsbench** [comment]
You might be right, either way I'll update it to mention the localization patches as well.

**Comment by pangolp** [comment]
Do we merge it and then have it update or do we wait for it to update?

**Comment by heyitsbench** [comment]
> Do we merge it and then have it update or do we wait for it to update?

I'm so sorry, I completely forgot that this PR was still open. I have added the note about localizations into the PR now.

**Comment by pangolp** [comment]
Thanks @heyitsbench.

**Pull request merged**
