### PR TITLE
Update and Create getting-started

### PR DESCRIPTION
**Pull request by Tony931023**
Update  getting-started and Create  es/getting-started 

#619

### CODE REVIEW

**Comment by Helias** [comment]
@pangolp please review

**Review by pangolp — APPROVED** [review]
The truth is that I did not read everything in detail, but I did read much of the information. I think it is something we can add and as I always say. If in the future, it can be written differently, it can be changed/improved. But many of the files that are being added today do not exist. I would add them, and if something appears, in any case it can be improved later.

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
Merge conflicts to solve :S

**Comment by Tony931023** [comment]
@Helias conflicts ok

**Comment by Kitzunu** [comment]
You need to make sure that you encode your files with UTF-8 or the wiki breaks. I just removed some of them. Feel free to re-PR them but with the right encoding

**Pull request merged**
