### PR TITLE
Update Install-with-Docker.md

### PR DESCRIPTION
**Pull request by d3s0x86**

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
That's only for MAC

**Comment by FrancescoBorzi** [comment]
correct @BarbzYHOOL , I did some modifications and now it's ready to be merged

**Comment by Yehonal** [comment]
@BarbzYHOOL PR are not so bad for wiki at the end 😅

**Comment by BarbzYHOOL** [comment]
for now we just lost tons of links and time

but maybe in the future it will pay off, so yes @Yehonal 

btw the issue template is not really useful imo, because it's only text and the best description for a PR is to check the modified files, no?

**Pull request merged**
